apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink }}
  food: {{ .Values.favorite.food }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borja-nginx
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: borja-nginx
  template:
    metadata:
      labels:
        app: borja-nginx
    spec:
      containers:
        - name: borja-nginx
          image: nginx:{{ .Values.nginx.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort:  {{ .Values.nginx.port }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: borja-nginx-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: borja-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.nginx.port }}
  type: LoadBalancer
